// <auto-generated />
namespace MyShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddCUstomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCUstomer));
        
        string IMigrationMetadata.Id
        {
            get { return "202304271021159_AddCUstomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
